library(reshape2)
temp <- tempfile()
url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url, destfile = temp, method = "curl")
plotdata <- read.csv(unz(temp, "household_power_consumption.txt"),header = F, skip=66637, nrows=2880, sep = ";" )
unlink(temp)
plotdata$datetime <- with(plotdata, as.POSIXct(paste(V1, V2), format = "%d/%m/%Y %H:%M:%S"))
d <- melt(subset(plotdata[,7:10]), id.vars = "datetime")
png(file = "plot4.png")
par(mfrow = c(2,2))
with(plotdata, {
  plot (datetime, V3, ylab="Global Active Power", xlab="", type = "l")
  plot(datetime, V5, ylab="Voltage", type = "l")
  with(d,plot(datetime, value, type = "n", xlab = "", ylab = "Energy sub metering"))
  with(subset(d,variable == "V7"), points(datetime, value, col = "black", type = "l"))
  with(subset(d,variable == "V8"), points(datetime, value, col = "red", type = "l"))
  with(subset(d,variable == "V9"), points(datetime, value, col = "blue", type = "l"))
  legend("topright", lty = 1, col = c("black", "red","blue"), legend = c("sub_metering_1","sub_metering_2","sub_metering_3") )
  plot(datetime, V4, ylab="Global_reactive_power", type = "l")
})
dev.off()